"""Change monto to integer

Revision ID: 64336c7bc311
Revises: 730989028736
Create Date: 2026-05-26 18:46:40.516077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64336c7bc311'
down_revision = '730989028736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.alter_column('monto',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.alter_column('monto',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
